name: totp_authentication_app
description: "totp authentication app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  pinput: ^5.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_bloc: ^8.1.5 
  otp: ^3.1.4
  flutter_secure_storage: ^9.2.0
  get_it: ^7.7.0 
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/